version: "3"

tasks:
  get:
    cmds:
      - go get -v
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test -v ./...
      - go test -race -v ./...
      - if [ $(go env GOOS) = 'linux' ]; then go test -asan -v ./...; fi
      - if [ $(go env GOOS) = 'linux' ]; then go test -msan -v ./...; fi
  build:
    cmds:
      - go build -o build/ltop .
